version: "3"

services:
  web:
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: local/expertsystem:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "on-failure"
    ports:
      - "${APP_PORT:-80}:80"
    env_file:
      - ../.env
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - "../src:/code/src"
