version: "3"

services:
  web:
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: "${DOCKER_IMAGE}:latest"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "on-failure"
    ports:
      - "${APP_PORT:-80}:80"
    env_file:
      - ../.env
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - "../src:/code/src"
      - "../alembic.ini:/code/alembic.ini"
    networks:
      - internal

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "${DB_PORT_EXT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
