"""Add Workflow Categories.

Revision ID: 3971bcd9a6e7
Revises: c2a1408ecbee
Create Date: 2022-11-03 13:01:45.727887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3971bcd9a6e7'
down_revision = 'c2a1408ecbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_categories',
    sa.Column('id', src.models._base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_categories_code'), 'workflow_categories', ['code'], unique=False)
    op.create_index(op.f('ix_workflow_categories_name'), 'workflow_categories', ['name'], unique=False)
    op.add_column('workflows', sa.Column('category_id', src.models._base.GUID(), nullable=True))
    op.create_index(op.f('ix_workflows_category_id'), 'workflows', ['category_id'], unique=False)
    op.create_foreign_key(None, 'workflows', 'workflow_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_index(op.f('ix_workflows_category_id'), table_name='workflows')
    op.drop_column('workflows', 'category_id')
    op.drop_index(op.f('ix_workflow_categories_name'), table_name='workflow_categories')
    op.drop_index(op.f('ix_workflow_categories_code'), table_name='workflow_categories')
    op.drop_table('workflow_categories')
    # ### end Alembic commands ###
