"""Add name attr to Run.

Revision ID: 45b8c2f9de40
Revises: 58158515d583
Create Date: 2022-11-10 12:55:51.238523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b8c2f9de40'
down_revision = '58158515d583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_runs_name'), 'runs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_name'), table_name='runs')
    op.drop_column('runs', 'name')
    # ### end Alembic commands ###
