"""Add platform Workspaces and Default WS for Users.

Revision ID: 4e583ecc0689
Revises: 7ea8588fb86e
Create Date: 2023-11-27 19:52:48.464956

"""
from alembic import op
import sqlalchemy as sa
from src.config import DB_SCHEMA, DB_PLATFORM_SCHEMA


# revision identifiers, used by Alembic.
revision = '4e583ecc0689'
down_revision = '7ea8588fb86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcb_workspaces',
    sa.Column('ws_id', sa.Integer(), nullable=False),
    sa.Column('ws_name', sa.String(), nullable=True),
    sa.Column('ws_description', sa.String(), nullable=True),
    sa.Column('ws_type', sa.String(), nullable=True),
    sa.Column('ws_owner', sa.String(), nullable=True),
    sa.Column('ws_status', sa.String(), nullable=True),
    sa.Column('ws_role', sa.String(), nullable=True),
    sa.Column('ws_created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ws_id'),
    schema=DB_PLATFORM_SCHEMA
    )
    op.create_index(op.f(f'ix_{DB_PLATFORM_SCHEMA}_mcb_workspaces_ws_id'), 'mcb_workspaces', ['ws_id'], unique=False, schema=DB_PLATFORM_SCHEMA)
    op.create_table('mcb_user_default_workspace',
    sa.Column('usr_def_ws_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('ws_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ws_id'], [f'{DB_PLATFORM_SCHEMA}.mcb_workspaces.ws_id'], ),
    sa.PrimaryKeyConstraint('usr_def_ws_id'),
    schema=DB_PLATFORM_SCHEMA
    )
    op.create_index(op.f(f'ix_{DB_PLATFORM_SCHEMA}_mcb_user_default_workspace_usr_def_ws_id'), 'mcb_user_default_workspace', ['usr_def_ws_id'], unique=False, schema=DB_PLATFORM_SCHEMA)
    op.create_index(op.f(f'ix_{DB_PLATFORM_SCHEMA}_mcb_user_default_workspace_ws_id'), 'mcb_user_default_workspace', ['ws_id'], unique=False, schema=DB_PLATFORM_SCHEMA)
    op.drop_constraint('files_user_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], source_schema=DB_SCHEMA, referent_schema=DB_SCHEMA)
    op.drop_constraint('modules_category_id_fkey', 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'module_categories', ['category_id'], ['id'], source_schema=DB_SCHEMA, referent_schema=DB_SCHEMA)
    op.drop_constraint('runs_workflow_id_fkey', 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'workflows', ['workflow_id'], ['id'], source_schema=DB_SCHEMA, referent_schema=DB_SCHEMA)
    op.drop_constraint('variables_features_feature_id_fkey', 'variables_features', type_='foreignkey')
    op.drop_constraint('variables_features_variable_id_fkey', 'variables_features', type_='foreignkey')
    op.create_foreign_key(None, 'variables_features', 'features', ['feature_id'], ['id'], source_schema=DB_SCHEMA, referent_schema=DB_SCHEMA)
    op.create_foreign_key(None, 'variables_features', 'variables', ['variable_id'], ['id'], source_schema=DB_SCHEMA, referent_schema=DB_SCHEMA)
    op.drop_constraint('workflows_category_id_fkey', 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'workflow_categories', ['category_id'], ['id'], source_schema=DB_SCHEMA, referent_schema=DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', schema=DB_SCHEMA, type_='foreignkey')
    op.create_foreign_key('workflows_category_id_fkey', 'workflows', 'workflow_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'variables_features', schema=DB_SCHEMA, type_='foreignkey')
    op.drop_constraint(None, 'variables_features', schema=DB_SCHEMA, type_='foreignkey')
    op.create_foreign_key('variables_features_variable_id_fkey', 'variables_features', 'variables', ['variable_id'], ['id'])
    op.create_foreign_key('variables_features_feature_id_fkey', 'variables_features', 'features', ['feature_id'], ['id'])
    op.drop_constraint(None, 'runs', schema=DB_SCHEMA, type_='foreignkey')
    op.create_foreign_key('runs_workflow_id_fkey', 'runs', 'workflows', ['workflow_id'], ['id'])
    op.drop_constraint(None, 'modules', schema=DB_SCHEMA, type_='foreignkey')
    op.create_foreign_key('modules_category_id_fkey', 'modules', 'module_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'files', schema=DB_SCHEMA, type_='foreignkey')
    op.create_foreign_key('files_user_id_fkey', 'files', 'users', ['user_id'], ['id'])
    op.drop_index(op.f(f'ix_{DB_PLATFORM_SCHEMA}_mcb_user_default_workspace_ws_id'), table_name='mcb_user_default_workspace', schema=DB_PLATFORM_SCHEMA)
    op.drop_index(op.f(f'ix_{DB_PLATFORM_SCHEMA}_mcb_user_default_workspace_usr_def_ws_id'), table_name='mcb_user_default_workspace', schema=DB_PLATFORM_SCHEMA)
    op.drop_table('mcb_user_default_workspace', schema=DB_PLATFORM_SCHEMA)
    op.drop_index(op.f(f'ix_{DB_PLATFORM_SCHEMA}_mcb_workspaces_ws_id'), table_name='mcb_workspaces', schema=DB_PLATFORM_SCHEMA)
    op.drop_table('mcb_workspaces', schema=DB_PLATFORM_SCHEMA)
    # ### end Alembic commands ###
