"""Add variables and features

Revision ID: 705e25f1cad5
Revises: a50a8a5511b2
Create Date: 2023-02-08 18:38:42.575198

"""
from alembic import op
import sqlalchemy as sa
from src.models._base import GUID


# revision identifiers, used by Alembic.
revision = '705e25f1cad5'
down_revision = 'a50a8a5511b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='expert_system'
    )
    op.create_index(op.f('ix_expert_system_features_name'), 'features', ['name'], unique=False, schema='expert_system')
    op.create_table('variables',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='expert_system'
    )
    op.create_index(op.f('ix_expert_system_variables_name'), 'variables', ['name'], unique=False, schema='expert_system')
    op.create_table('variables_features',
    sa.Column('variable_id', GUID(), nullable=False),
    sa.Column('feature_id', GUID(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['expert_system.features.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['expert_system.variables.id'], ),
    sa.PrimaryKeyConstraint('variable_id', 'feature_id'),
    schema='expert_system'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables_features', schema='expert_system')
    op.drop_index(op.f('ix_expert_system_variables_name'), table_name='variables', schema='expert_system')
    op.drop_table('variables', schema='expert_system')
    op.drop_index(op.f('ix_expert_system_features_name'), table_name='features', schema='expert_system')
    op.drop_table('features', schema='expert_system')
    # ### end Alembic commands ###
