"""Update Variables and Features.

Revision ID: 7ea8588fb86e
Revises: 705e25f1cad5
Create Date: 2023-02-13 18:09:55.890065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea8588fb86e'
down_revision = '705e25f1cad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('mapi_id', sa.String(), nullable=True), schema='expert_system')
    op.create_index(op.f('ix_expert_system_features_mapi_id'), 'features', ['mapi_id'], unique=False, schema='expert_system')
    op.add_column('variables', sa.Column('mapi_id', sa.String(), nullable=True), schema='expert_system')
    op.create_index(op.f('ix_expert_system_variables_mapi_id'), 'variables', ['mapi_id'], unique=False, schema='expert_system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_system_variables_mapi_id'), table_name='variables', schema='expert_system')
    op.drop_column('variables', 'mapi_id', schema='expert_system')
    op.drop_index(op.f('ix_expert_system_features_mapi_id'), table_name='features', schema='expert_system')
    op.drop_column('features', 'mapi_id', schema='expert_system')
    # ### end Alembic commands ###
