"""Add stores property to workflows.

Revision ID: b1830af233ce
Revises: ce27faf6852e
Create Date: 2022-10-10 21:11:37.991417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1830af233ce"
down_revision = "ce27faf6852e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflows", sa.Column("stores", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflows", "stores")
    # ### end Alembic commands ###
