"""Add Modules and their Categories.

Revision ID: c2a1408ecbee
Revises: b1830af233ce
Create Date: 2022-11-02 12:02:28.106600

"""
from alembic import op
import sqlalchemy as sa
from src.models._base import GUID


# revision identifiers, used by Alembic.
revision = "c2a1408ecbee"
down_revision = "b1830af233ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module_categories",
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_module_categories_code"), "module_categories", ["code"], unique=False
    )
    op.create_index(
        op.f("ix_module_categories_name"), "module_categories", ["name"], unique=False
    )
    op.create_table(
        "modules",
        sa.Column("id", GUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category_id", GUID(), nullable=True),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("instructions", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["module_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modules_category_id"), "modules", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_modules_code"), "modules", ["code"], unique=True)
    op.create_index(op.f("ix_modules_name"), "modules", ["name"], unique=False)
    op.create_index(op.f("ix_modules_task"), "modules", ["task"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_modules_task"), table_name="modules")
    op.drop_index(op.f("ix_modules_name"), table_name="modules")
    op.drop_index(op.f("ix_modules_code"), table_name="modules")
    op.drop_index(op.f("ix_modules_category_id"), table_name="modules")
    op.drop_table("modules")
    op.drop_index(op.f("ix_module_categories_name"), table_name="module_categories")
    op.drop_index(op.f("ix_module_categories_code"), table_name="module_categories")
    op.drop_table("module_categories")
    # ### end Alembic commands ###
