"""reset all changes

Revision ID: cb1d53933ec6
Revises: 
Create Date: 2024-02-15 16:48:19.108841

"""
from alembic import op
import sqlalchemy as sa
import src.models._base


# revision identifiers, used by Alembic.
revision = 'cb1d53933ec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('mapi_id', sa.String(), nullable=True),
        sa.Column('info', sa.JSON(), nullable=True),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_features_mapi_id'), 'features', ['mapi_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_features_name'), 'features', ['name'], unique=False, schema='public')
    op.create_table('mcb_workspaces',
        sa.Column('ws_id', sa.Integer(), nullable=False),
        sa.Column('ws_name', sa.String(), nullable=True),
        sa.Column('ws_description', sa.String(), nullable=True),
        sa.Column('ws_type', sa.String(), nullable=True),
        sa.Column('ws_owner', sa.String(), nullable=True),
        sa.Column('ws_status', sa.String(), nullable=True),
        sa.Column('ws_role', sa.String(), nullable=True),
        sa.Column('ws_created_on', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('ws_id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_mcb_workspaces_ws_id'), 'mcb_workspaces', ['ws_id'], unique=False, schema='public')
    op.create_table('module_categories',
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_module_categories_code'), 'module_categories', ['code'], unique=False, schema='public')
    op.create_index(op.f('ix_public_module_categories_name'), 'module_categories', ['name'], unique=False, schema='public')
    op.create_table('users',
        sa.Column('sub', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('info', sa.JSON(), nullable=True),
        sa.Column('permission', sa.JSON(), nullable=True),
        sa.Column('session', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index('ix_expert_system_users_sub_provider', 'users', ['sub', 'provider'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_is_active'), 'users', ['is_active'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_provider'), 'users', ['provider'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_sub'), 'users', ['sub'], unique=False, schema='public')
    op.create_table('variables',
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('mapi_id', sa.String(), nullable=True),
        sa.Column('info', sa.JSON(), nullable=True),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_variables_mapi_id'), 'variables', ['mapi_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_variables_name'), 'variables', ['name'], unique=False, schema='public')
    op.create_table('workflow_categories',
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_workflow_categories_code'), 'workflow_categories', ['code'], unique=False, schema='public')
    op.create_index(op.f('ix_public_workflow_categories_name'), 'workflow_categories', ['name'], unique=False, schema='public')
    op.create_table('files',
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('search', sa.Text(), nullable=True),
        sa.Column('info', sa.JSON(), nullable=True),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ws_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['ws_id'], ['public.mcb_workspaces.ws_id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_files_ws_id'), 'files', ['ws_id'], unique=False, schema='public')
    op.create_table('mcb_user_default_workspace',
        sa.Column('usr_def_ws_id', sa.Integer(), nullable=False),
        sa.Column('user_name', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('updated_on', sa.DateTime(), nullable=True),
        sa.Column('ws_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['ws_id'], ['public.mcb_workspaces.ws_id'], ),
        sa.PrimaryKeyConstraint('usr_def_ws_id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_mcb_user_default_workspace_usr_def_ws_id'), 'mcb_user_default_workspace', ['usr_def_ws_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_mcb_user_default_workspace_ws_id'), 'mcb_user_default_workspace', ['ws_id'], unique=False, schema='public')
    op.create_table('modules',
        sa.Column('category_id', src.models._base.GUID(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('task', sa.String(), nullable=False),
        sa.Column('instructions', sa.JSON(), nullable=True),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['public.module_categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_modules_category_id'), 'modules', ['category_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_modules_code'), 'modules', ['code'], unique=True, schema='public')
    op.create_index(op.f('ix_public_modules_name'), 'modules', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_modules_task'), 'modules', ['task'], unique=False, schema='public')
    op.create_table('variables_features',
        sa.Column('variable_id', src.models._base.GUID(), nullable=False),
        sa.Column('feature_id', src.models._base.GUID(), nullable=False),
        sa.ForeignKeyConstraint(['feature_id'], ['public.features.id'], ),
        sa.ForeignKeyConstraint(['variable_id'], ['public.variables.id'], ),
        sa.PrimaryKeyConstraint('variable_id', 'feature_id'),
        schema='public'
    )
    op.create_table('workflows',
        sa.Column('category_id', src.models._base.GUID(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('tasks', sa.JSON(), nullable=True),
        sa.Column('stores', sa.JSON(), nullable=True),
        sa.Column('raw_diagram_data', sa.JSON(), nullable=True),
        sa.Column('is_template', sa.Boolean(), nullable=False),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ws_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['public.workflow_categories.id'], ),
        sa.ForeignKeyConstraint(['ws_id'], ['public.mcb_workspaces.ws_id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_workflows_category_id'), 'workflows', ['category_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_workflows_is_template'), 'workflows', ['is_template'], unique=False, schema='public')
    op.create_index(op.f('ix_public_workflows_name'), 'workflows', ['name'], unique=True, schema='public')
    op.create_index(op.f('ix_public_workflows_ws_id'), 'workflows', ['ws_id'], unique=False, schema='public')
    op.create_table('runs',
        sa.Column('workflow_id', src.models._base.GUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('state', sa.JSON(), nullable=True),
        sa.Column('steps', sa.JSON(), nullable=True),
        sa.Column('queue', sa.JSON(), nullable=True),
        sa.Column('id', src.models._base.GUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('ws_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['workflow_id'], ['public.workflows.id'], ),
        sa.ForeignKeyConstraint(['ws_id'], ['public.mcb_workspaces.ws_id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='public'
    )
    op.create_index(op.f('ix_public_runs_name'), 'runs', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_runs_workflow_id'), 'runs', ['workflow_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_runs_ws_id'), 'runs', ['ws_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_runs_ws_id'), table_name='runs', schema='public')
    op.drop_index(op.f('ix_public_runs_workflow_id'), table_name='runs', schema='public')
    op.drop_index(op.f('ix_public_runs_name'), table_name='runs', schema='public')
    op.drop_table('runs', schema='public')
    op.drop_index(op.f('ix_public_workflows_ws_id'), table_name='workflows', schema='public')
    op.drop_index(op.f('ix_public_workflows_name'), table_name='workflows', schema='public')
    op.drop_index(op.f('ix_public_workflows_is_template'), table_name='workflows', schema='public')
    op.drop_index(op.f('ix_public_workflows_category_id'), table_name='workflows', schema='public')
    op.drop_table('workflows', schema='public')
    op.drop_table('variables_features', schema='public')
    op.drop_index(op.f('ix_public_modules_task'), table_name='modules', schema='public')
    op.drop_index(op.f('ix_public_modules_name'), table_name='modules', schema='public')
    op.drop_index(op.f('ix_public_modules_code'), table_name='modules', schema='public')
    op.drop_index(op.f('ix_public_modules_category_id'), table_name='modules', schema='public')
    op.drop_table('modules', schema='public')
    op.drop_index(op.f('ix_public_mcb_user_default_workspace_ws_id'), table_name='mcb_user_default_workspace', schema='public')
    op.drop_index(op.f('ix_public_mcb_user_default_workspace_usr_def_ws_id'), table_name='mcb_user_default_workspace', schema='public')
    op.drop_table('mcb_user_default_workspace', schema='public')
    op.drop_index(op.f('ix_public_files_ws_id'), table_name='files', schema='public')
    op.drop_table('files', schema='public')
    op.drop_index(op.f('ix_public_workflow_categories_name'), table_name='workflow_categories', schema='public')
    op.drop_index(op.f('ix_public_workflow_categories_code'), table_name='workflow_categories', schema='public')
    op.drop_table('workflow_categories', schema='public')
    op.drop_index(op.f('ix_public_variables_name'), table_name='variables', schema='public')
    op.drop_index(op.f('ix_public_variables_mapi_id'), table_name='variables', schema='public')
    op.drop_table('variables', schema='public')
    op.drop_index(op.f('ix_public_users_sub'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_provider'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_is_active'), table_name='users', schema='public')
    op.drop_index('ix_expert_system_users_sub_provider', table_name='users', schema='public')
    op.drop_table('users', schema='public')
    op.drop_index(op.f('ix_public_module_categories_name'), table_name='module_categories', schema='public')
    op.drop_index(op.f('ix_public_module_categories_code'), table_name='module_categories', schema='public')
    op.drop_table('module_categories', schema='public')
    op.drop_index(op.f('ix_public_mcb_workspaces_ws_id'), table_name='mcb_workspaces', schema='public')
    op.drop_table('mcb_workspaces', schema='public')
    op.drop_index(op.f('ix_public_features_name'), table_name='features', schema='public')
    op.drop_index(op.f('ix_public_features_mapi_id'), table_name='features', schema='public')
    op.drop_table('features', schema='public')
    # ### end Alembic commands ###
