"""Add new column to handle raw bpmn data in Workflow.

Revision ID: ce27faf6852e
Revises: 022e779e4b17
Create Date: 2022-08-30 12:52:58.275229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce27faf6852e'
down_revision = '022e779e4b17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('raw_diagram_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'raw_diagram_data')
    # ### end Alembic commands ###
