"""Add User model

Revision ID: d721fd138a69
Revises: 29077ddb7045
Create Date: 2022-12-29 20:57:13.874956

"""
from alembic import op
import sqlalchemy as sa
from src.models._base import GUID


# revision identifiers, used by Alembic.
revision = 'd721fd138a69'
down_revision = '29077ddb7045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('info', sa.JSON(), nullable=True),
    sa.Column('permission', sa.JSON(), nullable=True),
    sa.Column('session', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='expert_system'
    )
    op.create_index(op.f('ix_expert_system_users_is_active'), 'users', ['is_active'], unique=False, schema='expert_system')
    op.create_index(op.f('ix_expert_system_users_provider'), 'users', ['provider'], unique=False, schema='expert_system')
    op.create_index(op.f('ix_expert_system_users_sub'), 'users', ['sub'], unique=False, schema='expert_system')
    op.create_index('ix_expert_system_users_sub_provider', 'users', ['sub', 'provider'], unique=False, schema='expert_system')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expert_system_users_sub_provider', table_name='users', schema='expert_system')
    op.drop_index(op.f('ix_expert_system_users_sub'), table_name='users', schema='expert_system')
    op.drop_index(op.f('ix_expert_system_users_provider'), table_name='users', schema='expert_system')
    op.drop_index(op.f('ix_expert_system_users_is_active'), table_name='users', schema='expert_system')
    op.drop_table('users', schema='expert_system')
    # ### end Alembic commands ###
