"""run models

Revision ID: fce4385f872c
Revises: aaefb8fd201e
Create Date: 2024-05-26 21:27:09.471908

"""
from alembic import op
import sqlalchemy as sa

import src


# revision identifiers, used by Alembic.
revision = 'fce4385f872c'
down_revision = 'aaefb8fd201e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_run_actions',
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('input', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ws_id', sa.Boolean(), nullable=True),
    sa.Column('id', src.models._base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_new_run_actions_action_id'), 'new_run_actions', ['action_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_run_actions_action_type'), 'new_run_actions', ['action_type'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_run_actions_input'), 'new_run_actions', ['input'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_run_actions_status'), 'new_run_actions', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_run_actions_value'), 'new_run_actions', ['value'], unique=False, schema='public')
    op.create_table('new_runs',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('ws_id', sa.Boolean(), nullable=True),
    sa.Column('is_part_of_other', sa.Boolean(), nullable=True),
    sa.Column('json_representation', sa.JSON(), nullable=True),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', src.models._base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_new_runs_action'), 'new_runs', ['action'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_runs_status'), 'new_runs', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_runs_step'), 'new_runs', ['step'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_runs_title'), 'new_runs', ['title'], unique=False, schema='public')
    op.create_index(op.f('ix_public_new_runs_workflow_id'), 'new_runs', ['workflow_id'], unique=False, schema='public')
    op.drop_constraint('files_ws_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'mcb_workspaces', ['ws_id'], ['ws_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('mcb_user_default_workspace_ws_id_fkey', 'mcb_user_default_workspace', type_='foreignkey')
    op.create_foreign_key(None, 'mcb_user_default_workspace', 'mcb_workspaces', ['ws_id'], ['ws_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('modules_category_id_fkey', 'modules', type_='foreignkey')
    op.create_foreign_key(None, 'modules', 'module_categories', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('new_workflows_ws_id_fkey', 'new_workflows', type_='foreignkey')
    op.create_foreign_key(None, 'new_workflows', 'mcb_workspaces', ['ws_id'], ['ws_id'], source_schema='public', referent_schema='public')
    op.drop_constraint('runs_workflow_id_fkey', 'runs', type_='foreignkey')
    op.drop_constraint('runs_ws_id_fkey', 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'mcb_workspaces', ['ws_id'], ['ws_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'runs', 'workflows', ['workflow_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('variables_features_feature_id_fkey', 'variables_features', type_='foreignkey')
    op.drop_constraint('variables_features_variable_id_fkey', 'variables_features', type_='foreignkey')
    op.create_foreign_key(None, 'variables_features', 'variables', ['variable_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'variables_features', 'features', ['feature_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('workflows_category_id_fkey', 'workflows', type_='foreignkey')
    op.drop_constraint('workflows_ws_id_fkey', 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'mcb_workspaces', ['ws_id'], ['ws_id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'workflows', 'workflow_categories', ['category_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'workflows', schema='public', type_='foreignkey')
    op.create_foreign_key('workflows_ws_id_fkey', 'workflows', 'mcb_workspaces', ['ws_id'], ['ws_id'])
    op.create_foreign_key('workflows_category_id_fkey', 'workflows', 'workflow_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'variables_features', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'variables_features', schema='public', type_='foreignkey')
    op.create_foreign_key('variables_features_variable_id_fkey', 'variables_features', 'variables', ['variable_id'], ['id'])
    op.create_foreign_key('variables_features_feature_id_fkey', 'variables_features', 'features', ['feature_id'], ['id'])
    op.drop_constraint(None, 'runs', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'runs', schema='public', type_='foreignkey')
    op.create_foreign_key('runs_ws_id_fkey', 'runs', 'mcb_workspaces', ['ws_id'], ['ws_id'])
    op.create_foreign_key('runs_workflow_id_fkey', 'runs', 'workflows', ['workflow_id'], ['id'])
    op.drop_constraint(None, 'new_workflows', schema='public', type_='foreignkey')
    op.create_foreign_key('new_workflows_ws_id_fkey', 'new_workflows', 'mcb_workspaces', ['ws_id'], ['ws_id'])
    op.drop_constraint(None, 'modules', schema='public', type_='foreignkey')
    op.create_foreign_key('modules_category_id_fkey', 'modules', 'module_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'mcb_user_default_workspace', schema='public', type_='foreignkey')
    op.create_foreign_key('mcb_user_default_workspace_ws_id_fkey', 'mcb_user_default_workspace', 'mcb_workspaces', ['ws_id'], ['ws_id'])
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key('files_ws_id_fkey', 'files', 'mcb_workspaces', ['ws_id'], ['ws_id'])
    op.drop_index(op.f('ix_public_new_runs_workflow_id'), table_name='new_runs', schema='public')
    op.drop_index(op.f('ix_public_new_runs_title'), table_name='new_runs', schema='public')
    op.drop_index(op.f('ix_public_new_runs_step'), table_name='new_runs', schema='public')
    op.drop_index(op.f('ix_public_new_runs_status'), table_name='new_runs', schema='public')
    op.drop_index(op.f('ix_public_new_runs_action'), table_name='new_runs', schema='public')
    op.drop_table('new_runs', schema='public')
    op.drop_index(op.f('ix_public_new_run_actions_value'), table_name='new_run_actions', schema='public')
    op.drop_index(op.f('ix_public_new_run_actions_status'), table_name='new_run_actions', schema='public')
    op.drop_index(op.f('ix_public_new_run_actions_input'), table_name='new_run_actions', schema='public')
    op.drop_index(op.f('ix_public_new_run_actions_action_type'), table_name='new_run_actions', schema='public')
    op.drop_index(op.f('ix_public_new_run_actions_action_id'), table_name='new_run_actions', schema='public')
    op.drop_table('new_run_actions', schema='public')
    # ### end Alembic commands ###
